### PR TITLE
Feature/locking unlocking vehicle

### PR DESCRIPTION
**Pull request by mtomasic2**
Enhanced the backend functionality to include the implementation of locking and unlocking vehicles. Users now have the capability to secure and release vehicles through the backend system. This feature provides a robust and secure mechanism for managing the lock status of vehicles.

### CODE REVIEW

**Review by iplavsic20 — APPROVED** [review]
Good job :)

**Review by dsantek20 — APPROVED** [review]
Good code

**Review by ijelovic20 — APPROVED** [review]
Great

**Review by jsmoljanec — APPROVED** [review]
Good work👍🏼👏🏻

**Pull request merged**
