### PR TITLE
Feature/calculate statistics

### PR DESCRIPTION
**Pull request by mtomasic2**
Implemented a robust system for calculating and storing vehicle statistics. This enhancement involves computing the fuel consumption for each reservation and updating the cumulative distance traveled by the vehicle. Now, the system accurately tracks the amount of fuel consumed during each reservation, contributing to a more comprehensive overview of the vehicle's usage history.

### CODE REVIEW

**Review by dsantek20 — APPROVED** [review]
Very nice

**Review by jsmoljanec — APPROVED** [review]
Great work!

**Review by iplavsic20 — APPROVED** [review]
Great job :)

**Review by ijelovic20 — APPROVED** [review]
Good job

**Pull request merged**
